### ISSUE TITLE
library doesn't work LOL

### ISSUE THREAD

**Issue by AndrewRayCode** [dmolsen/CSS3-Snowflakes#2]
https://github.com/dmolsen/CSS3-Snowflakes/blob/master/js/snowflakes.js#L69

should be `this.` LOLOLOLOL

**Comment by dmolsen** [comment]
I'm curious which browser it didn't work in. Can you let me know? It should be `this.` and I'm surprised it's still working for me in Safari, Chrome and FF. _shrugs_ thanks for the heads up. I know someone else took the code and did a real clean-up. I was trying to learn JS patterns (and still am) when writing this up.
